dataset_path: parquet
dataset_kwargs:
  data_files:
    dev: "/workdir/important_datasets/CABBAGE/wikiHow/dev-00000-of-00001.parquet"
    test: "/workdir/important_datasets/CABBAGE/wikiHow/test-00000-of-00001.parquet"
    validation: "/workdir/important_datasets/CABBAGE/wikiHow/validation-00000-of-00001.parquet"

task: "CABBAGE_wikiHow"
test_split: dev
#validation_split: dev
output_type: generate_until
doc_to_visual: !function utils.CABBAGE_doc_to_visual
doc_to_text: !function utils.CABBAGE_doc_to_text
doc_to_target: "answer"

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0.1
  do_sample: False

metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.gpt_eval_aggregation
    higher_is_better: true

  - metric: passing_adjusted_score
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

process_results: !function utils.CABBAGE_process_results_gpt_eval

metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    format: default
    pre_prompt: ""
    post_prompt: ""
